//
//  Constant.swift
//  newbaluchon
//
//  Created by Fiona on 30/05/2019.
//  Copyright © 2019 clement. All rights reserved.
//

import Foundation
struct Constant {
    // MARK: - PROPERTIES WEATHER
    //key: 2567298816d0d1f85b5a7edfdc58aa63,"aa9e109ce2968dabc49a4e7bda426532"
    static var weatherUrl = URL(string: "http://api.openweathermap.org/data/2.5/weather")!
    static var apiKeyWeather = "2567298816d0d1f85b5a7edfdc58aa63"
    static var dataWeatherHoliday = [WeatherHoliday]()
    static var unit = "metric"
    static var weatherUrlCity = URL(string: "http://bulk.openweathermap.org/sample/city.list.json.gz")!

    // MARK: - properties translate
    static var translateUrl = URL(string: "https://translation.googleapis.com/language/translate/v2")!
    static var apiKeyTranslate = "AIzaSyDX07xWgK_IQRN3wXHFBopwycC9AzachOU"

    // MARK: - properties moneyConvertEur
    static var moneyUrl = URL(string: "http://data.fixer.io/api/latest")!
    static var apiKeyMoney = "64c9be90700082a08ab21d1f2cef1132"

    // MARK: - properties moneyRecupArrayDevise
    static var deviseUrl = URL(string: "http://data.fixer.io/api/symbols")!
    static var apiKeyDevise = "64c9be90700082a08ab21d1f2cef1132"
    static var arrayDeviseSymbols = ["AED": "United Arab Emirates Dirham",
                                     "AFN": "Afghan Afghani",
                                     "ALL": "Albanian Lek",
                                     "AMD": "Armenian Dram",
                                     "ANG": "Netherlands Antillean Guilder",
                                     "AOA": "Angolan Kwanza",
                                     "ARS": "Argentine Peso",
                                     "AUD": "Australian Dollar",
                                     "AWG": "Aruban Florin",
                                     "AZN": "Azerbaijani Manat",
                                     "BAM": "Bosnia-Herzegovina Convertible Mark",
                                     "BBD": "Barbadian Dollar",
                                     "BDT": "Bangladeshi Taka",
                                     "BGN": "Bulgarian Lev",
                                     "BHD": "Bahraini Dinar",
                                     "BIF": "Burundian Franc",
                                     "BMD": "Bermudan Dollar",
                                     "BND": "Brunei Dollar",
                                     "BOB": "Bolivian Boliviano",
                                     "BRL": "Brazilian Real",
                                     "BSD": "Bahamian Dollar",
                                     "BTC": "Bitcoin",
                                     "BTN": "Bhutanese Ngultrum",
                                     "BWP": "Botswanan Pula",
                                     "BYN": "New Belarusian Ruble",
                                     "BYR": "Belarusian Ruble",
                                     "BZD": "Belize Dollar",
                                     "CAD": "Canadian Dollar",
                                     "CDF": "Congolese Franc",
                                     "CHF": "Swiss Franc",
                                     "CLF": "Chilean Unit of Account (UF)",
                                     "CLP": "Chilean Peso",
                                     "CNY": "Chinese Yuan",
                                     "COP": "Colombian Peso",
                                     "CRC": "Costa Rican Colón",
                                     "CUC": "Cuban Convertible Peso",
                                     "CUP": "Cuban Peso",
                                     "CVE": "Cape Verdean Escudo",
                                     "CZK": "Czech Republic Koruna",
                                     "DJF": "Djiboutian Franc",
                                     "DKK": "Danish Krone",
                                     "DOP": "Dominican Peso",
                                     "DZD": "Algerian Dinar",
                                     "EGP": "Egyptian Pound",
                                     "ERN": "Eritrean Nakfa",
                                     "ETB": "Ethiopian Birr",
                                     "EUR": "Euro",
                                     "FJD": "Fijian Dollar",
                                     "FKP": "Falkland Islands Pound",
                                     "GBP": "British Pound Sterling",
                                     "GEL": "Georgian Lari",
                                     "GGP": "Guernsey Pound",
                                     "GHS": "Ghanaian Cedi",
                                     "GIP": "Gibraltar Pound",
                                     "GMD": "Gambian Dalasi",
                                     "GNF": "Guinean Franc",
                                     "GTQ": "Guatemalan Quetzal",
                                     "GYD": "Guyanaese Dollar",
                                     "HKD": "Hong Kong Dollar",
                                     "HNL": "Honduran Lempira",
                                     "HRK": "Croatian Kuna",
                                     "HTG": "Haitian Gourde",
                                     "HUF": "Hungarian Forint",
                                     "IDR": "Indonesian Rupiah",
                                     "ILS": "Israeli New Sheqel",
                                     "IMP": "Manx pound",
                                     "INR": "Indian Rupee",
                                     "IQD": "Iraqi Dinar",
                                     "IRR": "Iranian Rial",
                                     "ISK": "Icelandic Króna",
                                     "JEP": "Jersey Pound",
                                     "JMD": "Jamaican Dollar",
                                     "JOD": "Jordanian Dinar",
                                     "JPY": "Japanese Yen",
                                     "KES": "Kenyan Shilling",
                                     "KGS": "Kyrgystani Som",
                                     "KHR": "Cambodian Riel",
                                     "KMF": "Comorian Franc",
                                     "KPW": "North Korean Won",
                                     "KRW": "South Korean Won",
                                     "KWD": "Kuwaiti Dinar",
                                     "KYD": "Cayman Islands Dollar",
                                     "KZT": "Kazakhstani Tenge",
                                     "LAK": "Laotian Kip",
                                     "LBP": "Lebanese Pound",
                                     "LKR": "Sri Lankan Rupee",
                                     "LRD": "Liberian Dollar",
                                     "LSL": "Lesotho Loti",
                                     "LTL": "Lithuanian Litas",
                                     "LVL": "Latvian Lats",
                                     "LYD": "Libyan Dinar",
                                     "MAD": "Moroccan Dirham",
                                     "MDL": "Moldovan Leu",
                                     "MGA": "Malagasy Ariary",
                                     "MKD": "Macedonian Denar",
                                     "MMK": "Myanma Kyat",
                                     "MNT": "Mongolian Tugrik",
                                     "MOP": "Macanese Pataca",
                                     "MRO": "Mauritanian Ouguiya",
                                     "MUR": "Mauritian Rupee",
                                     "MVR": "Maldivian Rufiyaa",
                                     "MWK": "Malawian Kwacha",
                                     "MXN": "Mexican Peso",
                                     "MYR": "Malaysian Ringgit",
                                     "MZN": "Mozambican Metical",
                                     "NAD": "Namibian Dollar",
                                     "NGN": "Nigerian Naira",
                                     "NIO": "Nicaraguan Córdoba",
                                     "NOK": "Norwegian Krone",
                                     "NPR": "Nepalese Rupee",
                                     "NZD": "New Zealand Dollar",
                                     "OMR": "Omani Rial",
                                     "PAB": "Panamanian Balboa",
                                     "PEN": "Peruvian Nuevo Sol",
                                     "PGK": "Papua New Guinean Kina",
                                     "PHP": "Philippine Peso",
                                     "PKR": "Pakistani Rupee",
                                     "PLN": "Polish Zloty",
                                     "PYG": "Paraguayan Guarani",
                                     "QAR": "Qatari Rial",
                                     "RON": "Romanian Leu",
                                     "RSD": "Serbian Dinar",
                                     "RUB": "Russian Ruble",
                                     "RWF": "Rwandan Franc",
                                     "SAR": "Saudi Riyal",
                                     "SBD": "Solomon Islands Dollar",
                                     "SCR": "Seychellois Rupee",
                                     "SDG": "Sudanese Pound",
                                     "SEK": "Swedish Krona",
                                     "SGD": "Singapore Dollar",
                                     "SHP": "Saint Helena Pound",
                                     "SLL": "Sierra Leonean Leone",
                                     "SOS": "Somali Shilling",
                                     "SRD": "Surinamese Dollar",
                                     "STD": "São Tomé and Príncipe Dobra",
                                     "SVC": "Salvadoran Colón",
                                     "SYP": "Syrian Pound",
                                     "SZL": "Swazi Lilangeni",
                                     "THB": "Thai Baht",
                                     "TJS": "Tajikistani Somoni",
                                     "TMT": "Turkmenistani Manat",
                                     "TND": "Tunisian Dinar",
                                     "TOP": "Tongan Paʻanga",
                                     "TRY": "Turkish Lira",
                                     "TTD": "Trinidad and Tobago Dollar",
                                     "TWD": "New Taiwan Dollar",
                                     "TZS": "Tanzanian Shilling",
                                     "UAH": "Ukrainian Hryvnia",
                                     "UGX": "Ugandan Shilling",
                                     "USD": "United States Dollar",
                                     "UYU": "Uruguayan Peso",
                                     "UZS": "Uzbekistan Som",
                                     "VEF": "Venezuelan Bolívar Fuerte",
                                     "VND": "Vietnamese Dong",
                                     "VUV": "Vanuatu Vatu",
                                     "WST": "Samoan Tala",
                                     "XAF": "CFA Franc BEAC",
                                     "XAG": "Silver (troy ounce)",
                                     "XAU": "Gold (troy ounce)",
                                     "XCD": "East Caribbean Dollar",
                                     "XDR": "Special Drawing Rights",
                                     "XOF": "CFA Franc BCEAO",
                                     "XPF": "CFP Franc",
                                     "YER": "Yemeni Rial",
                                     "ZAR": "South African Rand",
                                     "ZMK": "Zambian Kwacha (pre-2013)",
                                     "ZMW": "Zambian Kwacha",
                                     "ZWL": "Zimbabwean Dollar"] /*["STD", "INR", "XOF", "FKP", "AUD", "AFN", "NAD", "SHP", "MOP", "SRD", "GGP", "JEP", "UAH", "KYD", "JMD", "USD", "KRW", "AED", "XCD", "RON", "MNT", "CUC", "BYN", "XDR", "XAF", "ARS", "BSD", "BWP", "PYG", "DOP", "PHP", "SZL", "XPF", "BAM", "CDF", "GBP", "TJS", "OMR", "GNF", "GYD", "MWK", "MGA", "KPW", "ANG", "MDL", "ETB", "DKK", "HTG", "LSL", "NIO", "TZS", "MUR", "CLF", "LVL", "UYU", "SGD", "EUR", "SAR", "UGX", "ISK", "IMP", "KMF", "ZAR", "SYP", "BTN", "THB", "BDT", "GTQ", "GMD", "BHD", "BYR", "COP", "BRL", "PKR", "MVR", "YER", "LAK", "MAD", "IRR", "NGN", "JOD", "HKD", "SBD", "BOB", "GEL", "BTC", "TWD", "MKD", "LRD", "RWF", "AWG", "UZS", "PAB", "SLL", "MMK", "ZWL", "CAD", "TOP", "SDG", "VEF", "GIP", "RUB", "KGS", "VUV", "HRK", "AOA", "BBD", "TMT", "CLP", "MXN", "JPY", "CHF", "SEK", "LYD", "VND", "TTD", "CZK", "GHS", "RSD", "ZMW", "XAU", "TRY", "FJD", "KHR", "NZD", "WST", "IQD", "LBP", "BND", "KWD", "HUF", "BMD", "QAR", "MYR", "ALL", "PEN", "PLN", "CNY", "EGP", "NOK", "IDR", "LKR", "SOS", "ILS", "DZD", "PGK", "AMD", "BIF", "AZN", "BGN", "BZD", "MZN", "CRC", "SCR", "LTL", "SVC", "HNL", "TND", "KZT", "MRO", "CUP", "CVE", "ERN", "NPR", "DJF", "XAG", "ZMK", "KES"]*/
    static var arrayDeviseSymbolSource = ["EUR":"Europe"]
    // MARK: - properties Segue
    static var segueListeTableView = "listeTableViewWeather"
    static var segueSettingWeather = "enterCity"
    static var segueSettingHolidayWeather = "addCityHoliday"
    static var segueLanguageTableView = "choiceLanguage"
}
